In [2]:
"""
Задание 5.1
Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.
Вычислите, по возможности не используя программирование: (5E)〖〖〖^(-1)〗〗^ 〗^ где Е – единичная матрица размера 5х5.
"""
import numpy as np

A = 5 * np.identity(5)
print(A)

P = np.linalg.inv(A)
print(P)

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]
[[0.2 0.  0.  0.  0. ]
 [0.  0.2 0.  0.  0. ]
 [0.  0.  0.2 0.  0. ]
 [0.  0.  0.  0.2 0. ]
 [0.  0.  0.  0.  0.2]]


In [3]:
"""
Задание 5.2 Вычислите определитель
"""
a = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]], float)
print(a)
np.linalg.det(a)

[[1. 2. 3.]
 [4. 0. 6.]
 [7. 8. 9.]]


59.999999999999986

In [12]:
"""
Задание 5.3
1. Вычислите матрицу, обратную данной
2. Приведите пример матрицы 4х4, ранг которой равен 1.
"""
np.linalg.inv(a)

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

In [16]:
c = np.array([[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]], float)
print(c)
b = np.array([[1], [2], [3]], float)
np.linalg.matrix_rank(b, 0.0001)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


1

In [17]:
np.linalg.matrix_rank(a, 0.0001)

3

In [18]:
"""
Задание 5.4
Вычислите скалярное произведение двух векторов:  
(1, 5)  и  (2, 8)
"""
d = np.array([1, 5])
f = np.array([2, 8])
np.dot(d, f)

42

In [19]:
"""
Задание 5.5
(1, 5, 0), (2, 8, 7) и (7, 1.5, 3) Вычислите смешанное произведение трех векторов:
"""
g = np.array([1, 5, 0])
h = np.array([2, 8, 7])
j = np.array([7, 1.5, 3])
k = np.cross(g, h)
print(np.inner(k, j))

228.5


In [4]:
"""
Задание 6.1
Решите линейную систему
"""
import numpy as np

np.linalg.inv(a)
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]], float)
B = np.array([12, 2, 1])
x = np.linalg.solve(A, B)
print(x)

[-9.2         0.9         6.46666667]


In [23]:
"""
Задание 6.2
Найдите псевдорешение:
"""
C = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
D = np.array([1, 7, 12, 7, 15])
np.linalg.matrix_rank(C, 0.0001)

3

In [24]:
np.linalg.lstsq(C, D)

C:\Users\Filipp\AppData\Local\Temp/ipykernel_17872/3224479271.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(C, D)


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

In [25]:
x = np.dot(C, [1.13919353, -0.90498444, -0.9009803]) - D
print(x)
print(np.linalg.norm(x))

[-0.76979505  0.03751835 -0.16349016 -0.21671144  0.21805317]
0.8457139653464247


In [27]:
print(np.linalg.norm([1.13, -0.9, -0.9]))
print(np.linalg.norm([1.15, -0.95, -0.95]))

1.7020282018815083
1.7684739183827392


In [29]:
'''
Задание 6.3
Сколько решений имеет линейная система.
Если ноль – то измените вектор правой части так, чтобы система стала совместной, и решите ее. 
'''
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], float)
B = np.array([2, 5, 1], float)
C = np.array([[1, 2, 3, 2], [4, 5, 6, 5], [7, 8, 9, 1]], float)
print(np.linalg.matrix_rank(A, 0.0001))
print(np.linalg.matrix_rank(C, 0.0001))
np.linalg.solve(A, B)

2
3


array([-2.20676382e+16,  4.41352763e+16, -2.20676382e+16])

In [30]:
B = np.array([0, 0, 0], float)
np.linalg.solve(A, B)

array([ 0.,  0., -0.])

In [31]:
# Если решение x = [1, 1, 1]
B = np.array([6, 15, 24], float)
x = np.linalg.solve(A, B)
print(x)
print(np.dot(A, x) - B)

[-0.6  4.2 -0.6]
[0. 0. 0.]


In [32]:
print(np.dot(A, np.array([1, 1, 1], float)) - B)
C = np.array([[1, 2, 3, 6], [4, 5, 6, 15], [7, 8, 9, 24]], float)
print(np.linalg.matrix_rank(C, 0.0001))

[0. 0. 0.]
2


In [33]:
"""
Задание 6.4
Вычислите LU-разложение матрицы
"""
A = np.array([[1, 2, 3],
             [2, 16, 21],
             [4, 28, 73]])
np.linalg.det(A)

432.00000000000017

In [34]:
import scipy
import scipy.linalg
A = np.array([[1, 2, 3],
             [2, 16, 21],
             [4, 28, 73]], float)
P, L, U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


In [35]:
'''
Задание 6.5
Найдите нормальное псевдорешение недоопределенной системы:
x + 2y – z = 1  
8x – 5y + 2z = 12
Для этого определите функцию Q(x,y,z), равную норме решения, и найдите ее минимум. 
'''
A = np.array([[1, 2, -1],
             [8, -5, 2]], float)
B = np.array([1, 12])
np.linalg.lstsq(A, B)

C:\Users\Filipp\AppData\Local\Temp/ipykernel_17872/1526640301.py:11: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(A, B)


(array([ 1.38191882, -0.18081181,  0.0202952 ]),
 array([], dtype=float64),
 2,
 array([9.65316119, 2.41173777]))

In [36]:
print(np.dot(A, [1.38191882, -0.18081181,  0.0202952 ]))

[ 1.         12.00000001]


In [37]:
"""
Задание 6.6
Найдите одно из псевдорешений вырожденной системы
Попробуйте также отыскать и нормальное псевдорешение.
"""
A = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]], float)
B = np.array([2, 5, 11], float)
C = np.array([[1, 2, 3, 2], [4, 5, 6, 5], [7, 8, 9, 11]], float)
print(np.linalg.matrix_rank(A, 0.0001))
print(np.linalg.matrix_rank(C, 0.0001))

2
3


In [39]:
Q, R = np.linalg.qr(A)
print(Q)
print(R)
print(np.dot(Q, R))

[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.11164740e-15]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [41]:
R1 = R[:2, :2]
R1

array([[-8.1240384 , -9.6011363 ],
       [ 0.        ,  0.90453403]])

In [42]:
B1 = np.dot(np.transpose(Q), B)[:2]
B1

array([-1.21860576e+01,  8.54871729e-15])

In [43]:
X1 = np.linalg.solve(R1, B1)
print(X1)
X = np.append(X1, 0)
print(X)
np.linalg.norm(X), np.linalg.norm(np.dot(A, X) - B)

[1.50000000e+00 9.45096256e-15]
[1.50000000e+00 9.45096256e-15 0.00000000e+00]


(1.4999999999999893, 1.2247448713915885)

In [44]:
np.linalg.lstsq(A, B)

C:\Users\Filipp\AppData\Local\Temp/ipykernel_17872/1844739126.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(A, B)


(array([ 1.25,  0.5 , -0.25]),
 array([], dtype=float64),
 2,
 array([1.68481034e+01, 1.06836951e+00, 1.40266540e-16]))

In [45]:
X = [1.25, 0.5, -0.25]
np.linalg.norm(X), np.linalg.norm(np.dot(A, X) - B)

(1.3693063937629153, 1.224744871391589)